// Code generated by the go generate ./... command; DO NOT EDIT.

package version

import "fmt"

var ver *Version

func init() {
	ver = &Version{
		Version:    "v0.0.1-dev",
		CommitHash: "f2bf447ee86d392c028b364dfb7026d49b45de0d",
		Date:       "2023-12-03T20:54:42Z",
		Signature:  "3YiWEz9MSFH3MAiX5v6yu2mrjBM3NMR5Bj3Q57j6iYzG",
	}
}

type Version struct {
	Version    string `json:"version"`
	CommitHash string `json:"commitHash"`
	Date       string `json:"date"`
	Signature  string `json:"signature"`
}

func GetVersion() *Version {
	return ver
}

func GetVersionString() string {
	return fmt.Sprintf("version: %s, commit: %s, date: %s, uuid: %s", ver.Version, ver.CommitHash, ver.Date, ver.Signature)
}
